# Generated by Django 5.2.5 on 2025-08-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guset',
            new_name='Guest',
        ),
    ]
